version: '3.3'

services:
  stability-ai:
    container_name: sd
    ports:
      - '5000:5000'
    image: 'r8.im/stability-ai/stable-diffusion@sha256:3080f37ef32771c9984d65033cbe71caa96c69680008bae64cf691724a6df04c'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  stable-diffusion-ui:
    container_name: sd-ui
    ports:
      - '8000:8000'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - stability-ai

networks:
  default: