name: Check JavaScript for conformance with Prettier

on:
  push:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - name: Run prettier
      run: |-
        npm run prettier-fix
    - name: Print the required changes
      run: git diff; git reset --hard
    - name: Check prettier
      run: |-
        npm run prettier-check