name: Check JavaScript for conformance with Prettier

on:
  push:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - uses: actionsx/prettier@v2
      with:
        # prettier CLI arguments.
        args: --check \"./**/*.js\" --config .prettierrc.json