name: Check JavaScript for conformance with Prettier

on:
  push:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - uses: actionsx/prettier@v2
      with:
        # prettier CLI arguments.
        args: --print-width 120 --tab-width 4 --no-semi --arrow-parens always --trailing-comma es5 --write "./**/*.js"
    - uses: GrantBirki/git-diff-action@vX.X.X
      id: git-diff-action
      with:
        json_diff_file_output: diff.json
        raw_diff_file_output: diff.txt
    - name: print raw diff
      env:
        DIFF: ${{ steps.git-diff-action.outputs.raw-diff-path }}
      run: cat $DIFF